### ISSUE TITLE
Failed to load MKL libraries

### ISSUE THREAD

**Issue by igorpisarev** [imagej/ops-experiments#9]
I tried running the MKL deconvolution example and ran into the following error:
```
Intel MKL FATAL ERROR: cannot load libmkl_vml_avx2.so or libmkl_vml_def.so.
```

I'm using Ubuntu 16.04 and have the latest version of MKL installed in the default location `/opt/intel/mkl/`. Compilation with maven executes just fine, and then when I run the `InteractiveMKLDeconvolveTest` program, it crashes with the above error presumably when the first native call is attempted.

Both of the library files that fail to load actually exist in `/opt/intel/mkl/lib/intel64/`. I tried supplying this directory to the program with `-Djava.library.path` but it didn't affect anything.

Is there something I'm missing in the configuration?

**Comment by bnorthan** [comment]
Hi Igor

The only thing I'm doing differently is setting the library path in my .bashrc file.  I am also adding the /opt/intel/lib/intel64 path.  I don't know if that is going to help you though, as that if for OMP stuff. 
 
export LD_LIBRARY_PATH="/opt/intel/mkl/lib/intel64/:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="/opt/intel/lib/intel64/:$LD_LIBRARY_PATH"

Then I've been running using this command... 

mvn exec:java -Dexec.mainClass="net.imagej.ops.experiments.filter.deconvolve.InteractiveCudaDeconvolveTest"

If I run through maven I can make it work without adding anything to the library path.  This is because javacpp collects all the dependencies and puts them here 

/ops-experiments-mkl/target/classes/net/imagej/ops/experiments/filter/deconvolve/linux-x86_64

I end up with the below libraries in the 'linux-x86_64' 

libiomp5.so                         libmkl_avx512.so  libmkl_gnu_thread.so    libmkl_mc.so
libjniMKLRichardsonLucyWrapper.so*  libmkl_avx.so     libmkl_intel_lp64.so    libmkl_rt.so
libmkl_avx2.so                      libmkl_core.so    libmkl_intel_thread.so
libmkl_avx512_mic.so                libmkl_def.so     libmkl_mc3.so

Just out of curiousity, after you build, do you get the same set of libs copied into this directory??

I'm going to try updating MKL to the latest version and see if that makes a difference, I'll let you know.

**Comment by igorpisarev** [comment]
Hi @bnorthan, thanks for your quick reply!
I got it to work after setting the `LD_LIBRARY_PATH` as you suggested. (the first path `/opt/intel/mkl/lib/intel64/` was enough to make it work)

Interestingly, I do have the same copies of the library files in the target folder and in the resulting .jar file after running maven even if I don't explicitly set `LD_LIBRARY_PATH`, but the program itself works only if the library path is provided.

Do you know if there is a way to make it use the copies of the library files embedded into the .jar file, so that it can be distributed without having to install MKL on a target machine?

**Comment by bnorthan** [comment]
Hi @igorpisarev 

JavaCpp is actually pretty great for that.  Things should work without changing the path because all the information it needs is contained in annotations for example see [MKLRichardsonLucyWrapper](https://github.com/imagej/ops-experiments/blob/master/ops-experiments-mkl/src/main/java/net/imagej/ops/experiments/filter/deconvolve/MKLRichardsonLucyWrapper.java)

There are probably multiple ways to set this up ([MKL link advisor](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) can be useful for figuring out what to link depending on you operating system and threading model).  What I have done is linked to ```mkl_rt``` which in turn loads the libraries needed at run time.  The 'preload' variable specifies what will be needed at run time, then JavaCpp collects everything and will pack it into the jar during the build.  So theoretically everything should be distributed and there is no need to install MKL. 

So I think the issue you ran into was that it was looking for the `vml` version of a couple of libraries.  I'm not sure why.  Could be because you are using a different version of MKL.  I would try adding any libraries that it's complaining about to the 'preload' list.  Then they should get packed into the jar. 

Let me know how it works and if you have any more questions.

**Comment by igorpisarev** [comment]
Thanks Brian! It somehow didn't occur to me that there are `vml` versions of certain libraries in addition to the regular ones. So these two libraries were indeed missing in the jar because their `vml` versions were not on the preload list. I added them there and it works now without having to specify `LD_LIBRARY_PATH`.
I will create a PR with the changes.
